### ISSUE TITLE
Memory explode

### ISSUE THREAD

**Issue by izuna385** [MurtyShikhar/Hierarchical-Typing#2]
When I set dataset configuration *typenet* by setting 

`deploy.py`

```
def get_params():
    parser = argparse.ArgumentParser(description = 'Entity linker')
    parser.add_argument('-dataset', action="store", default="typenet", dest="dataset", type=str)
    parser.add_argument('-model_name', action="store", default="entity_linker", dest="model_name", type=str)
```
 and ran code, memory exploded. 
Although I changed https://github.com/MurtyShikhar/Hierarchical-Typing/blob/master/src/deploy.py#L374
to
`typenet_matrix = np.ones((len(type_dict), len(type_dict)), dtype='float32')`

but same things happened. I'll try another configuration.

**Comment by izuna385** [comment]
In https://github.com/MurtyShikhar/Hierarchical-Typing/blob/master/src/deploy.py#L374
the dim is  (153231, 153231) , and this may cause
`
Traceback (most recent call last):
  File "deploy.py", line 377, in <module>
    typenet_matrix = np.ones((len(type_dict), len(type_dict)))
  File "/home/cl/hiroshi-ho/.pyenv/versions/anaconda3-5.1.0/lib/python3.6/site-packages/numpy/core/numeric.py", line 188, in ones
    a = empty(shape, dtype, order)
MemoryError
`


Maybe this huge matrix causes memory explosion.
